server {
    listen 80;
    server_name _;
    server_tokens off;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/security-headers.conf;

    location / {
        include /etc/nginx/security-headers.conf;
        try_files $uri /index.html;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location = /service-worker.js {
        include /etc/nginx/security-headers.conf;
        expires -1;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        try_files $uri =404;
    }

    location = /manifest.json {
        include /etc/nginx/security-headers.conf;
        expires -1;
        add_header Cache-Control "no-cache, must-revalidate";
        try_files $uri =404;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2)$ {
        include /etc/nginx/security-headers.conf;
        expires 30d;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }
}
