import jsPDF from "jspdf";
import { resolveMediaUrl } from "./mediaUrl";

const text = (value, fallback = "-") => String(value ?? "").trim() || fallback;
const money = (value) => Number(value || 0).toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const dateTime = (value) => {
  const date = value ? new Date(value) : new Date();
  return Number.isNaN(date.getTime()) ? "-" : date.toLocaleString("en-KE", { dateStyle: "long", timeStyle: "short" });
};

const imageData = (url) => new Promise((resolve, reject) => {
  const image = new Image();
  image.crossOrigin = "anonymous";
  image.onload = () => {
    const canvas = document.createElement("canvas");
    canvas.width = image.naturalWidth;
    canvas.height = image.naturalHeight;
    canvas.getContext("2d").drawImage(image, 0, 0);
    resolve(canvas.toDataURL("image/png"));
  };
  image.onerror = reject;
  image.src = resolveMediaUrl(url);
});

const numberWordsBelowThousand = (number) => {
  const ones = ["", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten", "Eleven", "Twelve", "Thirteen", "Fourteen", "Fifteen", "Sixteen", "Seventeen", "Eighteen", "Nineteen"];
  const tens = ["", "", "Twenty", "Thirty", "Forty", "Fifty", "Sixty", "Seventy", "Eighty", "Ninety"];
  if (number < 20) return ones[number];
  if (number < 100) return `${tens[Math.floor(number / 10)]} ${ones[number % 10]}`.trim();
  return `${ones[Math.floor(number / 100)]} Hundred ${number % 100 ? `and ${numberWordsBelowThousand(number % 100)}` : ""}`.trim();
};

export const amountInWords = (value) => {
  const numeric = Math.max(0, Number(value || 0));
  const amount = Math.floor(numeric);
  const cents = Math.round((numeric - amount) * 100);
  if (!amount) return `Zero Kenya Shillings${cents ? ` and ${numberWordsBelowThousand(cents)} Cents` : ""} Only`;
  const groups = [
    [1_000_000_000, "Billion"], [1_000_000, "Million"], [1_000, "Thousand"],
  ];
  let remainder = amount;
  const parts = [];
  groups.forEach(([unit, label]) => {
    if (remainder >= unit) {
      parts.push(`${numberWordsBelowThousand(Math.floor(remainder / unit))} ${label}`);
      remainder %= unit;
    }
  });
  if (remainder) parts.push(numberWordsBelowThousand(remainder));
  return `${parts.join(" ")} Kenya Shillings${cents ? ` and ${numberWordsBelowThousand(cents)} Cents` : ""} Only`;
};

const addHeader = async (doc, school, title) => {
  doc.setFillColor(15, 118, 110);
  doc.rect(0, 0, 210, 37, "F");
  if (school.logo_url || school.logo) {
    try { doc.addImage(await imageData(school.logo_url || school.logo), 14, 6, 24, 24, undefined, "FAST"); } catch { /* optional logo */ }
  }
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.text(doc.splitTextToSize(text(school.name, "Smart M Hub School"), 145), 43, 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const contacts = [school.address, school.phone, school.email].filter(Boolean).join(" | ");
  if (contacts) doc.text(doc.splitTextToSize(contacts, 150), 43, 21);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(title.toUpperCase(), 43, 31);
  doc.setTextColor(17, 24, 39);
};

const addFooter = (doc, schoolName) => {
  const pages = doc.getNumberOfPages();
  for (let page = 1; page <= pages; page += 1) {
    doc.setPage(page);
    doc.setDrawColor(203, 213, 225);
    doc.line(14, 286, 196, 286);
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text(`${text(schoolName, "Smart M Hub School")} | Generated by Smart M Hub`, 14, 291);
    doc.text(`Page ${page} of ${pages}`, 181, 291);
  }
};

const ensureSpace = async (doc, y, needed, school, title) => {
  if (y + needed <= 278) return y;
  doc.addPage();
  await addHeader(doc, school, title);
  return 46;
};

const gradeFor = (average) => average >= 80 ? "EE" : average >= 60 ? "ME" : average >= 40 ? "AE" : "BE";

export async function downloadAssessmentReportPdf(report, currentUser = {}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const school = report?.school_details || {};
  const learner = report?.learner_details || {};
  await addHeader(doc, school, "Student Assessment Report");
  let y = 45;
  doc.setFontSize(9.5);
  const meta = [
    ["Academic Year", report?.academic_year], ["Term", report?.term],
    ["Examination / Assessment", report?.exam_name], ["Report Date", dateTime(report?.report_date || report?.published_at || report?.updated_at)],
    ["Student", learner.full_name], ["Admission Number", learner.admission_number],
    ["Class", report?.class_name || learner.class_name], ["Stream", report?.stream || learner.stream],
  ];
  meta.forEach(([label, value], index) => {
    const column = index % 2;
    const row = Math.floor(index / 2);
    const x = column ? 108 : 14;
    const rowY = y + row * 9;
    doc.setFont("helvetica", "bold"); doc.text(`${label}:`, x, rowY);
    doc.setFont("helvetica", "normal"); doc.text(doc.splitTextToSize(text(value), 65)[0], x + 35, rowY);
  });
  y += 41;
  const areas = Array.isArray(report?.learning_areas) ? report.learning_areas : [];
  doc.setFillColor(226, 232, 240); doc.rect(14, y - 5, 182, 8, "F");
  doc.setFont("helvetica", "bold");
  [[16, "Subject / Learning Area"], [91, "Marks"], [111, "Maximum"], [137, "Grade"], [158, "Teacher Comment"]].forEach(([x, label]) => doc.text(label, x, y));
  y += 8;
  let total = 0; let maximumTotal = 0; let scored = 0;
  for (const [index, area] of areas.entries()) {
    y = await ensureSpace(doc, y, 14, school, "Student Assessment Report");
    const score = Number(area.score);
    const maximum = Number(area.max_marks ?? area.maximum_marks ?? 100);
    if (Number.isFinite(score)) { total += score; maximumTotal += maximum; scored += 1; }
    const commentLines = doc.splitTextToSize(text(area.teacher_remarks), 37);
    const height = Math.max(9, commentLines.length * 4.2 + 3);
    if (index % 2 === 0) { doc.setFillColor(248, 250, 252); doc.rect(14, y - 5, 182, height, "F"); }
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(text(area.name || area.learning_area), 68), 16, y);
    doc.text(Number.isFinite(score) ? String(score) : "-", 94, y);
    doc.text(Number.isFinite(maximum) ? String(maximum) : "-", 117, y);
    doc.text(text(area.grade || area.achievement_level || area.overall_grade), 140, y);
    doc.text(commentLines, 158, y);
    y += height;
  }
  y = await ensureSpace(doc, y, 70, school, "Student Assessment Report");
  const average = scored ? total / scored : 0;
  doc.setFillColor(236, 253, 245); doc.roundedRect(14, y, 182, 24, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.text(`Overall Total: ${scored ? `${total} / ${maximumTotal}` : "-"}`, 18, y + 8);
  doc.text(`Average Score: ${scored ? `${average.toFixed(2)}%` : "-"}`, 76, y + 8);
  doc.text(`Overall Grade: ${scored ? gradeFor(average) : "-"}`, 139, y + 8);
  if (report?.position != null) doc.text(`Position: ${report.position}`, 18, y + 17);
  const attendance = report?.attendance || {};
  if (Object.values(attendance).some((value) => value != null && value !== "")) {
    doc.text(`Attendance: ${text(attendance.days_present)} present / ${text(attendance.days_open)} days open; ${text(attendance.days_absent)} absent`, 76, y + 17);
  }
  y += 32;
  const comments = [
    ["Teacher", report?.teacher_name || currentUser.full_name || currentUser.name, report?.teacher_remarks],
    ["Class Teacher", report?.class_teacher_name, report?.class_teacher_remarks],
    ["Head Teacher / Principal", report?.principal_name || school.principal_name, report?.principal_remarks],
  ].filter(([, name, comment]) => name || comment);
  for (const [label, name, comment] of comments) {
    const lines = doc.splitTextToSize(text(comment), 140);
    y = await ensureSpace(doc, y, Math.max(16, lines.length * 4.5 + 11), school, "Student Assessment Report");
    doc.setFont("helvetica", "bold"); doc.text(`${label}: ${text(name)}`, 14, y);
    doc.setFont("helvetica", "normal"); doc.text(lines, 14, y + 6);
    y += Math.max(16, lines.length * 4.5 + 11);
  }
  const dates = [report?.closing_date || school.closing_date, report?.opening_date || school.opening_date];
  if (dates.some(Boolean)) { doc.text(`Closing Date: ${text(dates[0])}    Opening Date: ${text(dates[1])}`, 14, y); y += 10; }
  y = await ensureSpace(doc, y, 25, school, "Student Assessment Report");
  doc.text("Class Teacher: __________________", 14, y + 8);
  doc.text("Head Teacher / Principal: __________________", 72, y + 8);
  doc.text("Parent / Guardian: __________________", 145, y + 8);
  doc.text("Signature / Date", 14, y + 16); doc.text("Signature / Stamp / Date", 72, y + 16); doc.text("Signature / Date", 145, y + 16);
  addFooter(doc, school.name);
  doc.save(`${text(learner.admission_number, "assessment-report")}-assessment-report.pdf`);
}

export async function downloadPaymentReceiptPdf(payment, context = {}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const school = payment?.school_details || context.school || {
    name: payment?.school_name, logo_url: payment?.school_logo, address: payment?.school_address,
    phone: payment?.school_phone, email: payment?.school_email,
  };
  await addHeader(doc, school, "Official Payment Receipt");
  let y = 46;
  const student = context.student || {};
  const rows = [
    ["Receipt Number", payment?.receipt_number], ["Payment Date & Time", dateTime(payment?.created_at)],
    ["Student Name", payment?.student_name || student.full_name], ["Admission Number", payment?.admission_number || student.admission_number],
    ["Class", payment?.class_name || student.class_name], ["Stream", payment?.stream || student.stream],
    ["Parent / Payer", payment?.received_from], ["Fee Category / Purpose", String(payment?.payment_type || "").replaceAll("_", " ")],
    ["Academic Year", payment?.academic_year], ["Term", payment?.term],
    ["Payment Method", String(payment?.payment_method || "").replaceAll("_", " ")],
    ["Transaction Reference", payment?.transaction_reference || payment?.bank_reference || payment?.cheque_number || payment?.phone_number],
    ["Bank Reference", payment?.bank_reference], ["M-Pesa Phone", payment?.phone_number],
    ["Cheque Number", payment?.cheque_number], ["Payment Notes", payment?.description],
    ["Recorded By", payment?.recorded_by_name || payment?.submitted_by_name || payment?.submitted_by],
  ];
  doc.setFontSize(9.5);
  for (const [label, value] of rows) {
    y = await ensureSpace(doc, y, 10, school, "Official Payment Receipt");
    const lines = doc.splitTextToSize(text(value), 112);
    const height = Math.max(8, lines.length * 4.5 + 2);
    doc.setFillColor(y % 2 ? 248 : 241, 245, 249); doc.rect(14, y - 5, 182, height, "F");
    doc.setFont("helvetica", "bold"); doc.text(label, 17, y);
    doc.setFont("helvetica", "normal"); doc.text(lines, 77, y);
    y += height;
  }
  y = await ensureSpace(doc, y, 58, school, "Official Payment Receipt");
  const previousBalance = payment?.previous_balance ?? payment?.total_amount_due;
  doc.setFillColor(236, 253, 245); doc.roundedRect(14, y, 182, 31, 2, 2, "F");
  doc.setFont("helvetica", "bold");
  doc.text(`Previous Balance / Amount Due: KES ${money(previousBalance)}`, 18, y + 9);
  doc.text(`Amount Paid: KES ${money(payment?.amount)}`, 18, y + 18);
  doc.text(`Remaining Balance: KES ${money(payment?.outstanding_balance ?? payment?.balance_after_payment)}`, 18, y + 27);
  y += 39;
  doc.text("Amount in Words", 14, y); doc.setFont("helvetica", "normal");
  doc.text(doc.splitTextToSize(amountInWords(payment?.amount), 145), 49, y);
  y += 17;
  doc.text("Official Signature: __________________________", 14, y);
  doc.text("School Stamp: ______________________________", 110, y);
  addFooter(doc, school.name);
  doc.save(`${text(payment?.receipt_number, "payment-receipt")}.pdf`);
}
